### ISSUE TITLE
Automatisk kontering og dannelse af finansbilag vedr. salgsindtæger fra MobilePay PoS & MyShop

### ISSUE THREAD

**Issue by CSL-randers** [Randers-Kommune-Digitalisering/auto-mobilepaysalg-nordea-kmdopus#1]
```[tasklist]
### Tasks
- [x] Tilpasning af auth flow
- [x] Tilpasning af transaction flow
- [x] Tilpasning af konteringsregler
- [x] Tilpasning af frontend
- [x] Tilføjelse af log
- [ ] Lav tilføj regel-knap på frontend /konteringsregler
```

**Comment by CSL-randers** [comment]
Afventer Dev Support vedr. tokens

**Comment by CSL-randers** [comment]
NB: Reporting API har kun produktionsmiljø

**Comment by CSL-randers** [comment]
NB: Efter fusion mellem MobilePay og Vipps arbejdes der på ny opsætning af deres endpoints og auth løsning.

**Comment by CSL-randers** [comment]
PAS Borgerservice har snitflade hos Biometric, skal udelades fra programmet

**Comment by CSL-randers** [comment]
Projektet er nedlagt.
